name: Build

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.7'
    - run: "./bin/build.sh && git add -A && git commit -m 'Build triggered by Github Actions' && git push origin ${GITHUB_REF##*/}"
      shell: bash
