name: Deploy

# on:
  # schedule:
  #   # * is a special character in YAML so you have to quote this string
  #   - cron:  '*/15 * * * *'
  # release:
  #   type: [ published ]
  #   branches: [ master, staging ]

on: 
  workflow_dispatch:
  release:
    type: [ published ]
    branches: [ production ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.7'
    - run: "GIT_BRANCH=${{github.event.inputs.branch}} ./bin/deploy.sh"
      shell: bash
    # - name: Deploy via Webhook
    #   uses: distributhor/workflow-webhook
    #   with:
    #     url: "https://example.com/services/deploy.json"
    #     json: '{ "repo_url": "${{github.event.repository.html_url}}", "branch": "${{GITHUB_REF##*/}}", "api_key": "" }'
