name: Build

on: 
  workflow_dispatch:
    ref: ""

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.7'
    - run: "cd .. && echo $PWD && ls -al && ./bin/build.sh && git add -A && git commit -m 'Build triggered by Github Actions' && git push origin ${GITHUB_REF##*/}"
      shell: bash
